name: sv_env
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.5.4=py36h1de35cc_0
  - appdirs=1.4.3=py_1
  - appnope=0.1.0=py36_1000
  - asn1crypto=0.24.0=py36_1003
  - async-timeout=3.0.1=py_1000
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bcftools=1.9=h3a161e8_3
  - bcrypt=3.1.4=py36h470a237_0
  - bedtools=2.28.0=h7fd0a75_0
  - blast=2.7.1=boost1.64_3
  - bleach=3.1.0=py_0
  - boost=1.64.0=py36_4
  - boost-cpp=1.64.0=1
  - boto3=1.7.84=py_0
  - botocore=1.10.84=py_0
  - bwidget=1.9.11=1
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - cachetools=2.1.0=py_0
  - cairo=1.16.0=h9247486_1000
  - cctools=895=h7512d6f_0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.3=py36hccf1714_0
  - chardet=3.0.4=py36_1003
  - clang=4.0.1=h662ec87_0
  - clang_osx-64=4.0.1=h1ce6c1d_16
  - clangxx=4.0.1=hc9b4283_0
  - clangxx_osx-64=4.0.1=h22b1bf0_16
  - compiler-rt=4.0.1=h5487866_0
  - configargparse=0.13.0=py_1
  - cryptography=2.6.1=py36h212c5bf_0
  - curl=7.64.1=h22ea746_0
  - datrie=0.7.1=py36h1de35cc_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - docutils=0.14=py36_1001
  - dropbox=7.3.1=py36_0
  - entrypoints=0.3=py36_1000
  - filechunkio=1.6=py36_0
  - fontconfig=2.13.1=h1027ab8_1000
  - freetype=2.10.0=h24853df_0
  - ftputil=3.2=py36_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - gfortran_osx-64=4.8.5=h22b1bf0_8
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.11=py_0
  - glib=2.58.3=h2836805_1001
  - gmp=6.1.2=h0a44026_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - google-api-core=1.10.0=py36_0
  - google-auth=1.2.1=py_0
  - google-cloud-core=0.29.1=py_0
  - google-cloud-storage=1.15.0=py_0
  - google-resumable-media=0.3.2=py_0
  - googleapis-common-protos=1.5.9=py36_2
  - graphite2=1.3.13=h2098e52_1000
  - graphviz=2.40.1=ha626266_0
  - gsl=2.4=ha2d443c_1006
  - harfbuzz=2.4.0=h92b87b8_0
  - htslib=1.9=h3a161e8_7
  - icu=58.2=h0a44026_1000
  - idna=2.8=py36_1000
  - idna_ssl=1.1.0=py36_1000
  - ipykernel=5.1.0=py36h24bf2e0_1002
  - ipython=7.5.0=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py_0
  - jmespath=0.9.4=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.2.4=py_3
  - jupyter_core=4.4.0=py_0
  - krb5=1.16.3=hcfa6398_1001
  - ld64=274.2=h7c2db76_0
  - libblas=3.8.0=8_openblas
  - libcblas=3.8.0=8_openblas
  - libcurl=7.64.1=h16faf7d_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libdeflate=1.0=h1de35cc_1
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=0
  - libiconv=1.15=h01d97ff_1005
  - liblapack=3.8.0=8_openblas
  - libpng=1.6.37=h2573ce8_0
  - libprotobuf=3.7.1=hfbae3c0_0
  - libsodium=1.0.16=h1de35cc_1001
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.0.10=h79f4b77_1001
  - libxcb=1.13=h1de35cc_1002
  - libxml2=2.9.9=hd80cff7_0
  - llvm=4.0.1=hc748206_0
  - llvm-lto-tapi=4.0.1=h6701bc3_0
  - llvm-openmp=8.0.0=h770b8ee_0
  - make=4.2.1=h1de35cc_2004
  - markupsafe=1.1.1=py36h1de35cc_0
  - mistune=0.8.4=py36h1de35cc_1000
  - multidict=4.5.2=py36h1de35cc_1000
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - nettle=3.3=0
  - networkx=2.3=py_0
  - notebook=5.7.8=py36_0
  - numpy=1.16.3=py36hdf140aa_0
  - openblas=0.3.6=hd44dcd8_1
  - openssl=1.1.1b=h01d97ff_2
  - pandas=0.24.2=py36h0a44026_0
  - pandoc=2.7.2=0
  - pandocfilters=1.4.2=py_1
  - pango=1.40.14=h315e1c8_1004
  - paramiko=2.4.2=py36_1000
  - parso=0.4.0=py_0
  - pcre=8.41=h0a44026_1003
  - perl=5.22.0.1=0
  - perl-archive-tar=2.18=1
  - perl-list-moreutils=0.15=pl5.22.0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.1=py36_0
  - pixman=0.34.0=h1de35cc_1003
  - prettytable=0.7.2=py_3
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - protobuf=3.7.1=py36h6de7cb9_0
  - psutil=5.6.2=py36h01d97ff_0
  - pthread-stubs=0.4=h1de35cc_1001
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.4=py_1
  - pyasn1-modules=0.0.5=py36_0
  - pybedtools=0.8.0=py36h5c9b4e4_1
  - pycparser=2.19=py36_1
  - pygments=2.3.1=py_0
  - pygraphviz=1.3.1=py36_0
  - pynacl=1.3.0=py36h1de35cc_1000
  - pyrsistent=0.15.1=py36h01d97ff_0
  - pysam=0.15.2=py36h1719d13_3
  - pysftp=0.2.9=py36_0
  - python=3.6.7=h8dc6b48_1004
  - python-dateutil=2.8.0=py_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2019.1=py_0
  - pyvcf=0.6.8=py36_1000
  - pyyaml=5.1=py36h1de35cc_0
  - pyzmq=18.0.1=py36h2d07e9b_1
  - r-askpass=1.1=r351h46e59ec_0
  - r-assertthat=0.2.1=r351h6115d3f_0
  - r-backports=1.1.4=r351h159158b_0
  - r-base=3.5.1=h3f7eb4a_1006
  - r-base64enc=0.1_3=r351h46e59ec_1002
  - r-bedr=1.0.4=r351h6115d3f_1
  - r-bh=1.69.0_1=r351h6115d3f_0
  - r-boot=1.3_22=r351_0
  - r-broom=0.5.2=r351h6115d3f_0
  - r-callr=3.2.0=r351h6115d3f_0
  - r-caret=6.0_82=r351h159158b_0
  - r-cellranger=1.1.0=r351h6115d3f_1001
  - r-class=7.3_15=r351h46e59ec_1000
  - r-cli=1.1.0=r351h6115d3f_0
  - r-clipr=0.6.0=r351h6115d3f_0
  - r-cluster=2.0.8=r351haf69682_0
  - r-codetools=0.2_16=r351h6115d3f_1000
  - r-colorspace=1.4_1=r351h159158b_0
  - r-crayon=1.3.4=r351h6115d3f_1001
  - r-curl=3.3=r351h46e59ec_0
  - r-data.table=1.12.2=r351h159158b_0
  - r-dbi=1.0.0=r351h6115d3f_1001
  - r-dbplyr=1.4.0=r351h6115d3f_0
  - r-digest=0.6.18=r351h46e59ec_1000
  - r-dplyr=0.8.0.1=r351h466af19_1000
  - r-ellipsis=0.1.0=r351h46e59ec_0
  - r-essentials=3.5.1=r351_2000
  - r-evaluate=0.13=r351h6115d3f_1
  - r-fansi=0.4.0=r351h46e59ec_1000
  - r-forcats=0.4.0=r351h6115d3f_0
  - r-foreach=1.4.4=r351h6115d3f_1001
  - r-foreign=0.8_71=r351h46e59ec_1002
  - r-formatr=1.6=r351h6115d3f_0
  - r-fs=1.2.7=r351hf99fc2c_0
  - r-futile.logger=1.4.3=r351h6115d3f_1001
  - r-futile.options=1.0.1=r351h6115d3f_1000
  - r-generics=0.0.2=r351h6115d3f_1001
  - r-ggplot2=3.1.1=r351h6115d3f_0
  - r-gistr=0.4.2=r351h6115d3f_1001
  - r-glmnet=2.0_16=r351hfffe0aa_1001
  - r-glue=1.3.1=r351h159158b_0
  - r-gower=0.2.0=r351h46e59ec_0
  - r-gtable=0.3.0=r351h6115d3f_0
  - r-haven=2.1.0=r351h466af19_0
  - r-hexbin=1.27.2=r351hfffe0aa_1002
  - r-highr=0.8=r351h6115d3f_0
  - r-hms=0.4.2=r351h6115d3f_1000
  - r-htmltools=0.3.6=r351h0a44026_1002
  - r-htmlwidgets=1.3=r351h6115d3f_1000
  - r-httpuv=1.5.1=r351hf99fc2c_0
  - r-httr=1.4.0=r351h6115d3f_1000
  - r-ipred=0.9_8=r351h46e59ec_1000
  - r-irdisplay=0.7=r351_1000
  - r-irkernel=1.0.0=r351h6115d3f_0
  - r-iterators=1.0.10=r351h6115d3f_1001
  - r-jsonlite=1.6=r351h46e59ec_1000
  - r-kernsmooth=2.23_15=r351hfffe0aa_1002
  - r-knitr=1.22=r351h6115d3f_0
  - r-labeling=0.3=r351h6115d3f_1001
  - r-lambda.r=1.2.3=r351h6115d3f_1000
  - r-later=0.8.0=r351h466af19_0
  - r-lattice=0.20_38=r351h46e59ec_1000
  - r-lava=1.6.5=r351h6115d3f_0
  - r-lazyeval=0.2.2=r351h159158b_0
  - r-lubridate=1.7.4=r351h466af19_1001
  - r-magrittr=1.5=r351h6115d3f_1001
  - r-maps=3.3.0=r351h46e59ec_1002
  - r-markdown=0.9=r351h46e59ec_1000
  - r-mass=7.3_51.4=r351h159158b_0
  - r-matrix=1.2_17=r351h159158b_0
  - r-mgcv=1.8_28=r351h159158b_0
  - r-mime=0.6=r351h46e59ec_1000
  - r-modelmetrics=1.2.2=r351hf99fc2c_0
  - r-modelr=0.1.4=r351h6115d3f_0
  - r-munsell=0.5.0=r351h6115d3f_1001
  - r-nlme=3.1_139=r351haf69682_0
  - r-nnet=7.3_12=r351h46e59ec_1002
  - r-numderiv=2016.8_1=r351h6115d3f_1001
  - r-openssl=1.3=r351hdb18a49_0
  - r-pbdzmq=0.3_3=r351h583b4ea_1001
  - r-pillar=1.3.1=r351h6115d3f_1000
  - r-pkgconfig=2.0.2=r351h6115d3f_1001
  - r-plogr=0.2.0=r351h6115d3f_1001
  - r-plyr=1.8.4=r351h466af19_1002
  - r-praise=1.0.0=r351h6115d3f_1001
  - r-prettyunits=1.0.2=r351h6115d3f_1001
  - r-processx=3.3.0=r351h159158b_0
  - r-prodlim=2018.04.18=r351h466af19_1002
  - r-progress=1.2.0=r351h6115d3f_1002
  - r-promises=1.0.1=r351h466af19_1000
  - r-pryr=0.1.4=r351h466af19_1002
  - r-ps=1.3.0=r351h46e59ec_1000
  - r-purrr=0.3.2=r351h159158b_0
  - r-quantmod=0.4_13=r351h6115d3f_1000
  - r-r.methodss3=1.7.1=r351h6115d3f_1001
  - r-r.oo=1.22.0=r351h6115d3f_1000
  - r-r.utils=2.8.0=r351h6115d3f_0
  - r-r6=2.4.0=r351h6115d3f_0
  - r-randomforest=4.6_14=r351hfffe0aa_1000
  - r-rbokeh=0.5.0=r351h6115d3f_1001
  - r-rcolorbrewer=1.1_2=r351h6115d3f_1001
  - r-rcpp=1.0.1=r351hf99fc2c_0
  - r-rcpproll=0.3.0=r351h466af19_1000
  - r-readr=1.3.1=r351h466af19_1000
  - r-readxl=1.3.1=r351hf99fc2c_0
  - r-recipes=0.1.5=r351h6115d3f_0
  - r-recommended=3.5.1=r351_1001
  - r-rematch=1.0.1=r351h6115d3f_1001
  - r-repr=0.19.2=r351h6115d3f_0
  - r-reprex=0.2.1=r351h6115d3f_1000
  - r-reshape2=1.4.3=r351h466af19_1003
  - r-rlang=0.3.4=r351h159158b_0
  - r-rmarkdown=1.12=r351h6115d3f_0
  - r-rpart=4.1_15=r351h159158b_0
  - r-rstudioapi=0.10=r351h6115d3f_0
  - r-rvest=0.3.3=r351h6115d3f_0
  - r-scales=1.0.0=r351h466af19_1001
  - r-selectr=0.4_1=r351h6115d3f_1000
  - r-shiny=1.3.2=r351h6115d3f_0
  - r-sourcetools=0.1.7=r351h0a44026_1000
  - r-spatial=7.3_11=r351h46e59ec_1002
  - r-squarem=2017.10_1=r351h6115d3f_1001
  - r-stringi=1.4.3=r351hf99fc2c_0
  - r-stringr=1.4.0=r351h6115d3f_0
  - r-survival=2.44_1.1=r351h159158b_0
  - r-sys=3.2=r351h159158b_0
  - r-testthat=2.1.1=r351hf99fc2c_0
  - r-tibble=2.1.1=r351h159158b_0
  - r-tidyr=0.8.3=r351hf99fc2c_0
  - r-tidyselect=0.2.5=r351h466af19_1000
  - r-tidyverse=1.2.1=r351h6115d3f_1001
  - r-timedate=3043.102=r351h6115d3f_1000
  - r-tinytex=0.12=r351h6115d3f_0
  - r-ttr=0.23_4=r351hfffe0aa_1000
  - r-utf8=1.1.4=r351h46e59ec_1000
  - r-uuid=0.1_2=r351h46e59ec_1001
  - r-venndiagram=1.6.20=r351h6115d3f_1000
  - r-viridislite=0.3.0=r351h6115d3f_1001
  - r-whisker=0.3_2=r351h6115d3f_1001
  - r-withr=2.1.2=r351h6115d3f_1000
  - r-xfun=0.6=r351h6115d3f_0
  - r-xml2=1.2.0=r351h466af19_1002
  - r-xtable=1.8_3=r351_2000
  - r-xts=0.11_1=r351h46e59ec_1000
  - r-yaml=2.2.0=r351h46e59ec_1001
  - r-zoo=1.8_5=r351h159158b_0
  - ratelimiter=1.2.0=py36_1000
  - readline=7.0=hcfe32e1_1001
  - requests=2.13.0=py36_0
  - rsa=3.1.4=py36_0
  - s3transfer=0.1.13=py36_1001
  - samtools=1.9=h7c4ea83_11
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_1000
  - smmap2=2.0.5=py_0
  - snakemake=5.4.5=0
  - snakemake-minimal=5.4.5=py_0
  - sqlite=3.26.0=h1765d9f_1001
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=ha441bb4_1001
  - tktable=2.10=h1de35cc_0
  - tornado=6.0.2=py36h01d97ff_0
  - traitlets=4.3.2=py36_1000
  - typing_extensions=3.7.2=py36_1001
  - urllib3=1.12=py36_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.1=py36_0
  - wrapt=1.11.1=py36h1de35cc_0
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h1de35cc_1002
  - xorg-libice=1.0.9=h01d97ff_1004
  - xorg-libsm=1.2.3=h01d97ff_1000
  - xorg-libx11=1.6.7=h1de35cc_1000
  - xorg-libxau=1.0.9=h1de35cc_0
  - xorg-libxdmcp=1.1.3=h01d97ff_0
  - xorg-libxext=1.3.4=h01d97ff_0
  - xorg-libxrender=0.9.10=h01d97ff_1002
  - xorg-renderproto=0.11.1=h1de35cc_1002
  - xorg-xextproto=7.3.0=h1de35cc_1002
  - xorg-xproto=7.0.31=h1de35cc_1007
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - yarl=1.3.0=py36h1de35cc_1000
  - zeromq=4.3.1=h0a44026_1000
  - zlib=1.2.11=h1de35cc_1004
prefix: /Users/alexweber/miniconda3/envs/sv_env

